### ISSUE TITLE
Error while accessing any function in react-native-bluetooth-classics library.

### ISSUE THREAD

**Issue by MrElectrouino** [kenjdavidson/react-native-bluetooth-classic-apps#10]
Hello,

While accessing the isBluetoothEnabled or other function. Im getting the error says 
> TypeError: Cannot read property 'isBluetoothEnabled' of null:

I have console the RNBluetoothClassic to check the available function but the value, Im getting is null.

**Error Log:**
![image](https://github.com/kenjdavidson/react-native-bluetooth-classic-apps/assets/78482765/8bfc925c-f547-46f8-afd4-0872fd392e2f)

**Packages Information:**
 "dependencies": {
    "expo": "~49.0.15",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-bluetooth-classic": "^1.60.0-rc6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },

**Android version**: 8.1.0
**Api level**: 26

**The code im using....**
`import { StatusBar } from "expo-status-bar";
import { useEffect, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { PermissionsAndroid } from "react-native";
import RNBluetoothClassic from "react-native-bluetooth-classic";

const requestAccessFineLocationPermission = async () => {
  const granted = await PermissionsAndroid.request(
    PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
    {
      title: "Access fine location required for discovery",
      message:
        "In order to perform discovery, you must enable/allow " +
        "fine location access.",
      buttonNeutral: "Ask Me Later",
      buttonNegative: "Cancel",
      buttonPositive: "OK",
    }
  );
  return granted === PermissionsAndroid.RESULTS.GRANTED;
};
export default function App() {
  const [permission, setPermission] = useState(false);
  useEffect(() => {
    if (requestAccessFineLocationPermission()) {
      setPermission(true);
    } else {
      setPermission(false);
    }
  }, []);

  const requestAccessbluethoothPermission = async () => {
    console.log("List of function: ", RNBluetoothClassic && RNBluetoothClassic);
    if (permission) {
      try {
        if (RNBluetoothClassic && RNBluetoothClassic.isBluetoothEnabled()) {
          const devices = await RNBluetoothClassic.startDiscovery();
          console.log("Discovered devices:", devices);
          await RNBluetoothClassic.cancelDiscovery();
          console.log("Bluetooth permissions granted");
        } else {
          console.log("Bluetooth permissions denied");
        }
      } catch (error) {
        console.error("Error requesting permissions:", error);
      }
    }
  };
  permission && requestAccessbluethoothPermission();

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working ond your app!</Text>
      {permission && <Text>Permission Recieved!</Text>}
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
`

**Comment by kenjdavidson** [comment]
I'm assuming your app didn't auto link the library properly. You'll have to confirm.

**Comment by MrElectrouino** [comment]
Yeah right, but I dont know what to do about it. how can I check it?

**Comment by kenjdavidson** [comment]
I'd say check the docs on react native. 
Retry installing the library. 
Debug the native module. 

Not sure what else would stop it from loading without debugging.

**Comment by MrElectrouino** [comment]
Okay, thanks. I will create a new project and try again.

By the way, whenever you're free, could you please provide me with some resources on how to debug native modules?

**Comment by kenjdavidson** [comment]
You need to open and run from android studio. There are tutorials all over the web.

**Comment by MrElectrouino** [comment]
Ok thanks will check... : )
